spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:security #jdbc:mysql://localhost:3306/security
    platform: h2
    name: users

  data:
    rest:
      base-path: api/

runtime:
  profile: usersvc #inMemory, usersvc, jdbc


app:
    props:
      centralized-auth: false