server:
  port: 8080

spring:
  application:
    name: zuul-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    enabled: true

zuul:
  routes:
    movie:
      path: /movie/**
      serviceId: movie-lookup-service/movie/**
#      url: http://localhost:8083/movie/
    user:
      path: /user/**
      serviceId: user-lookup-service/user/**
#      url: http://localhost:8082/user/
    rating:
      path: /rating/**
      serviceId: rating-service/rating/
#      url: http://localhost:8081/rating/